# Generated by Django 4.2.13 on 2024-06-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
